### ISSUE TITLE
AppImage doesn't contain JavaCheck

### ISSUE THREAD

**Issue by Scrumplex** [PolyMC/PolyMC#117]
### Operating System

Linux

### Description of bug

The AppImage doesn't contain JavaCheck (or rather can not be found by PolyMC). Java versions can't be selected because of that.

### Steps to reproduce

* Run AppImage in a terminal
* observe the error about JavaCheck.jar not being found

### Suspected cause

duh

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
https://jenkins.polymc.org/job/PolyMC/ws/AppDir/usr/share/polymc/jars/

It's contained in the AppImage.

This probably requires code changes to properly detect files present in the AppImage. However I have no clue how to do that, so if some AppImage wizard would like to help that'd be nice

**Comment by txtsd** [comment]
`Auto-detect` and `Test` both work fine for me when using the AppImage.

EDIT: On Arch

Could you paste your logs?

**Comment by ghost** [comment]
same on Gentoo, with default USE flags

**Comment by sorat0mo** [comment]
[PolyMC-4.log](https://github.com/PolyMC/PolyMC/files/7993574/PolyMC-4.log)

This is my log, failed to detect java version even if I manually set the local java binary path

**Comment by ghost** [comment]
This seems to be caused by a whole subset of distro-specific behaviors for AppImages.

This is not directly caused by PolyMC, it's likely due to some extra sandboxing feature added in your distribution's `fuse2` package.

**Comment by Scrumplex** [comment]
Looks like this was fixed

**Comment by Camotoy** [comment]
I believe I'm encountering this error. I get this log message when trying to run an instance using the latest AppImage:

```
Java path is:
/lib/jvm/java-1.11.0-openjdk-amd64/bin/java


Checking Java version...
Could not start java:
Error: Unable to access jarfile /usr/share/polymc/jars/JavaCheck.jar
```
Output of `uname -a`:
`Linux HOSTNAME 5.11.0-7620-generic #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Output of `cat /etc/lsb-release`:
```
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
```

Since it was mentioned, my `fuse2fs` package version is `1.45.7-1ubuntu2` and my `libfuse2` package version is `2.9.9-4ubuntu2`.

I'm happy to assist further if need be.

**Comment by Scrumplex** [comment]
We fixed this in our development builds. We will release 1.1.0 very soon

**Comment by DioEgizio** [comment]
> We fixed this in our development builds. We will release 1.1.0 very soon

Looks like it's not :P

**Comment by Lutitious** [comment]
`PolyMC version: 1.0.6-475c7065


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.224.68]

session.minecraft.net resolves to:
    [3.224.239.34, 52.205.99.166, 3.211.39.224]

textures.minecraft.net resolves to:
    [143.204.68.81, 143.204.68.123, 143.204.68.60, 143.204.68.43]

api.mojang.com resolves to:
    [108.138.210.89]


Minecraft folder is:
/home/k21060140/.local/share/PolyMC/instances/1.8.9/.minecraft


Java path is:
/home/k21060140/.local/bin/jdk8u322-b06/bin/java


Checking Java version...
Could not start java:
Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar


Check your PolyMC Java settings.
Clipboard copy at: 07 Mar 2022 14:38:50 +0000
`
OS: Ubuntu 20.04.3 LTS x86_64 
Kernel: 5.13.0-30-generic 
CPU: Intel i7-7700 (8) @ 4.200GHz 
GPU: Intel HD Graphics 630 
Memory: 15865MiB

**Comment by K0-RR** [comment]
I'm using v1.1.0 and this is not fixed, full log:
<details>

    0.021 D <> Log initialized.
    0.021 D "PolyMC" , (c) 2013-2021  "PolyMC Contributors\n© 2012-2021 MultiMC Contributors"
    0.021 D Version                    :  "1.1.0-9f8983b5"
    0.021 D Git commit                 :  "9f8983b570fe3ddb9f689e1223ff3d2c7fff8b53"
    0.022 D Git refspec                :  ""
    0.022 D Work dir before adjustment :  "/home/k0rr"
    0.022 D Work dir after adjustment  :  "/home/k0rr/.local/share/PolyMC"
    0.022 D Adjusted by                :  "/home/k0rr/.local/share/PolyMC"
    0.022 D Binary path                :  "/tmp/.mount_PolyMCEWIXBH/usr/bin"
    0.022 D Application root path      :  "/tmp/.mount_PolyMCEWIXBH/usr"
    0.022 D <> Paths set.
    0.339 D Detected default console font: "DejaVu Sans Mono" , substitutions: ""
    0.343 D <> Settings loaded.
    0.446 D Detecting proxy settings...
    0.446 D Using no proxy is an option!
    0.446 D <> Network done.
    0.464 D Your language is "en_US"
    0.464 D <> Translations loaded.
    0.495 D Started watching  "/home/k0rr/.local/share/PolyMC/icons"
    0.495 D <> Instance icons intialized.
    0.497 D <> Icon themes initialized.
    0.497 D Determining System Theme...
    0.498 D System theme seems to be: "fusion"
    0.498 D Considering theme from theme factory: "windows"
    0.498 D Considering theme from theme factory: "fusion"
    0.498 D System theme has been determined to be: "Fusion"
    0.498 D Loading theme "custom"
    0.498 D <> Widget themes initialized.
    0.499 D Instance path              :  "instances"
    0.502 D Loading Instances...
    0.502 D Discovering instances in "/home/k0rr/.local/share/PolyMC/instances"
    0.502 D <> Instances loaded.
    0.504 D Loading accounts...
    0.504 C "Failed to read the account list file (accounts.json)."
    0.504 D <> Accounts loaded.
    0.508 D <> Cache initialized.
    0.509 D Downloading Translations Index...
    0.509 D Task "NetJob(Translations Index)" starting for the first time
    0.510 D <> Icon theme set.
    0.511 D <> Application theme set.
    0.605 D Task "JavaListLoadTask(0x55a4672abaa0)" starting for the first time
    0.605 D Linux Java detection incomplete - defaulting to "java"
    0.606 D Probing the following Java paths: 
    0.606 D   "java"
    0.606 D   "/usr/lib/jvm/bellsoft-java17-full.x86_64/jre/bin/java"
    0.606 D   "/usr/lib/jvm/bellsoft-java17-full.x86_64/bin/java"
    0.606 D   "/usr/lib/jvm/jdk-17.0.2+8/jre/bin/java"
    0.606 D   "/usr/lib/jvm/jdk-17.0.2+8/bin/java"
    0.606 D   ""
    0.606 D Task "JavaCheckerJob(0x55a4672abc60)" starting for the first time
    0.606 D "Java detection"  started.
    0.607 D "Running java checker: java-jar /usr/share/jars/JavaCheck.jar"
    0.608 D "Running java checker: /usr/lib/jvm/bellsoft-java17-full.x86_64/jre/bin/java-jar /usr/share/jars/JavaCheck.jar"
    0.610 D "Running java checker: /usr/lib/jvm/bellsoft-java17-full.x86_64/bin/java-jar /usr/share/jars/JavaCheck.jar"
    0.612 D "Running java checker: /usr/lib/jvm/jdk-17.0.2+8/jre/bin/java-jar /usr/share/jars/JavaCheck.jar"
    0.613 D "Running java checker: /usr/lib/jvm/jdk-17.0.2+8/bin/java-jar /usr/share/jars/JavaCheck.jar"
    0.615 D "Running java checker: -jar /usr/share/jars/JavaCheck.jar"
    0.615 D Java checker has failed to start.
    0.615 D Process environment:
    0.616 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.616 D Native environment:
    0.616 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.616 D "Java detection" progress: 1 / 6
    0.690 D Downloading  "https://i18n.polymc.org/index_v2.json"
    0.746 D Java checker has failed to start.
    0.746 D Process environment:
    0.746 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.746 D Native environment:
    0.747 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.747 D "Java detection" progress: 2 / 6
    0.747 D Java checker has failed to start.
    0.747 D Process environment:
    0.747 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.747 D Native environment:
    0.747 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
    0.747 D "Java detection" progress: 3 / 6
    0.844 D Dir changed: "/home/k0rr/.local/share/PolyMC/translations"
    0.846 D STDOUT ""
    0.846 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
    0.846 D Java checker finished with status  QProcess::NormalExit  exit code  1
    0.846 D "Java detection" progress: 4 / 6
    0.847 D STDOUT ""
    0.847 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
    0.847 D Java checker finished with status  QProcess::NormalExit  exit code  1
    0.847 D "Java detection" progress: 5 / 6
    0.848 D STDOUT ""
    0.849 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
    0.849 D Java checker finished with status  QProcess::NormalExit  exit code  1
    0.849 D "Java detection" progress: 6 / 6
    0.849 D Task "JavaCheckerJob(0x55a4672abc60)" succeeded
    0.849 D Found the following valid Java installations:
    0.850 D Task "JavaListLoadTask(0x55a4672abaa0)" succeeded
    0.899 D Download succeeded: "https://i18n.polymc.org/index_v2.json"
    0.900 D Task "NetJob(Translations Index)" succeeded
    0.900 D Got translations index!
   17.256 D Task "JavaListLoadTask(0x7f1da4007160)" starting for the first time
   17.256 D Linux Java detection incomplete - defaulting to "java"
   17.257 D Probing the following Java paths: 
   17.257 D   "java"
   17.257 D   "/usr/lib/jvm/bellsoft-java17-full.x86_64/jre/bin/java"
   17.257 D   "/usr/lib/jvm/bellsoft-java17-full.x86_64/bin/java"
   17.257 D   "/usr/lib/jvm/jdk-17.0.2+8/jre/bin/java"
   17.257 D   "/usr/lib/jvm/jdk-17.0.2+8/bin/java"
   17.257 D   ""
   17.258 D Task "JavaCheckerJob(0x55a4675a67c0)" starting for the first time
   17.258 D "Java detection"  started.
   17.258 D "Running java checker: java-jar /usr/share/jars/JavaCheck.jar"
   17.262 D "Running java checker: /usr/lib/jvm/bellsoft-java17-full.x86_64/jre/bin/java-jar /usr/share/jars/JavaCheck.jar"
   17.265 D "Running java checker: /usr/lib/jvm/bellsoft-java17-full.x86_64/bin/java-jar /usr/share/jars/JavaCheck.jar"
   17.269 D "Running java checker: /usr/lib/jvm/jdk-17.0.2+8/jre/bin/java-jar /usr/share/jars/JavaCheck.jar"
   17.272 D "Running java checker: /usr/lib/jvm/jdk-17.0.2+8/bin/java-jar /usr/share/jars/JavaCheck.jar"
   17.274 D "Running java checker: -jar /usr/share/jars/JavaCheck.jar"
   17.274 D Java checker has failed to start.
   17.274 D Process environment:
   17.274 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.274 D Native environment:
   17.275 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.275 D "Java detection" progress: 1 / 6
   17.277 D Java checker has failed to start.
   17.277 D Process environment:
   17.277 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.277 D Native environment:
   17.278 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.278 D "Java detection" progress: 2 / 6
   17.279 D Java checker has failed to start.
   17.279 D Process environment:
   17.279 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LD_LIBRARY_PATH=", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.279 D Native environment:
   17.279 D ("APPDIR=/tmp/.mount_PolyMCEWIXBH", "APPIMAGE=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "ARGV0=/home/k0rr/Downloads/PolyMC-Linux-1.1.0-x86_64.AppImage", "BROWSER=/usr/bin/www-browser", "CANBERRA_DRIVER=pulse", "COLORTERM=truecolor", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "DESKTOP_AUTOSTART_ID=10a5ef7afe4056a8a8164712864913988800000024090030", "DESKTOP_SESSION=/usr/share/xsessions/cinnamon", "DISPLAY=:0", "GCONF_TMPDIR=/tmp", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1cec8f24_d8a3_41a6_ba65_baae2db54e93", "GNOME_TERMINAL_SERVICE=:1.103", "GTK_MODULES=canberra-gtk-module", "GTK_OVERLAY_SCROLLING=1", "G_FILENAME_ENCODING=@locale", "HISTCONTROL=ignoredups", "HISTSIZE=1000", "HOME=/home/k0rr", "HOSTNAME=mageia", "INPUTRC=/etc/inputrc", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8:en_US:en", "LC_ADDRESS=pl_PL.UTF-8", "LC_IDENTIFICATION=pl_PL.UTF-8", "LC_MEASUREMENT=pl_PL.UTF-8", "LC_MONETARY=pl_PL.UTF-8", "LC_NAME=pl_PL.UTF-8", "LC_NUMERIC=pl_PL.UTF-8", "LC_PAPER=pl_PL.UTF-8", "LC_SOURCED=1", "LC_TELEPHONE=pl_PL.UTF-8", "LESSCHARSET=koi8-r", "LESSOPEN=|/usr/bin/lesspipe.sh %s", "LOGNAME=k0rr", "LS_COLORS=", "MAIL=/var/spool/mail/k0rr", "META_CLASS=desktop", "MGA_MENU_STYLE=mageia", "NLSPATH=/usr/share/locale/%l/%N", "OWD=/home/k0rr", "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/k0rr/.local/bin:/home/k0rr/bin", "PWD=/home/k0rr", "QT5DOCDIR=/usr/share/doc/qt5", "QTDIR5=/usr/lib64/qt5", "SECSHELL=1", "SESSION_MANAGER=local/mageia:@/tmp/.ICE-unix/2409,unix/mageia:/tmp/.ICE-unix/2409", "SHELL=/usr/bin/fish", "SHLVL=1", "SSH_ASKPASS=/usr/libexec/openssh/ssh-askpass", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "SYSTEMD_PAGER=/usr/bin/less -FR", "TERM=xterm-256color", "TMP=/tmp", "TMPDIR=/tmp", "USER=k0rr", "VTE_VERSION=6202", "XAUTHORITY=/home/k0rr/.Xauthority", "XDG_CURRENT_DESKTOP=X-Cinnamon", "XDG_DATA_DIRS=/home/k0rr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_CLASS=user", "XDG_SESSION_DESKTOP=", "XDG_SESSION_ID=c2", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "XDG_SESSION_TYPE=x11", "XDG_VTNR=1", "XMODIFIERS=@im=none")
   17.279 D "Java detection" progress: 3 / 6
   17.280 D STDOUT ""
   17.280 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
   17.280 D Java checker finished with status  QProcess::NormalExit  exit code  1
   17.280 D "Java detection" progress: 4 / 6
   17.281 D STDOUT ""
   17.281 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
   17.281 D Java checker finished with status  QProcess::NormalExit  exit code  1
   17.281 D "Java detection" progress: 5 / 6
   17.281 D STDOUT ""
   17.281 W STDERR "Error: Unable to access jarfile /usr/share/jars/JavaCheck.jar\n"
   17.282 D Java checker finished with status  QProcess::NormalExit  exit code  1
   17.282 D "Java detection" progress: 6 / 6
   17.282 D Task "JavaCheckerJob(0x55a4675a67c0)" succeeded
   17.282 D Found the following valid Java installations:
   17.282 D Task "JavaListLoadTask(0x7f1da4007160)" succeeded

</details>

**Comment by sorat0mo** [comment]
![Screenshot_20220313_081448](https://user-images.githubusercontent.com/11853019/158039486-80490991-c82c-4ec4-a8b7-dca132354708.png)

I deleted the ~/.local/share/PolyMC folder to start new, this is what happened when I tried to put the java path manually.

Edit: After extracting PolyMC AppImage with `./PolyMC-Linux-1.1.0-x86_64.AppImage --appimage-extract` and copying the `jars` folder to my /usr/share folder, it worked:

![Screenshot_20220313_082003](https://user-images.githubusercontent.com/11853019/158039579-4537f7d2-dde7-47ad-827d-4188969ce99e.png)

**Comment by Scrumplex** [comment]
Okay I found the root issue.

**Comment by txtsd** [comment]
@sorat0mo @RDKRACZ @Rahul-Imran @Camotoy Can y'all try the [AppImage from here](https://github.com/PolyMC/PolyMC/actions/runs/1976242844) and see if the issue is fixed?

**Comment by K0-RR** [comment]
Tried it. It's working for me.

**Comment by Scrumplex** [comment]
Cool! For now I would recommend people use that AppImage instead of the latest stable version. The next release (1.1.1) will have this fix.

**Comment by Lutitious** [comment]
nice work, will try out tomorrow

**Comment by Stormersh** [comment]
> @sorat0mo @RDKRACZ @Rahul-Imran @Camotoy Can y'all try the [AppImage from here](https://github.com/PolyMC/PolyMC/actions/runs/1976242844) and see if the issue is fixed?

Can confirm, this fixes the issue

**Comment by luni3359** [comment]
I don't know what I'm doing wrong but I can't run this. When I download `PolyMC-Linux-1a535cf-Release-x86_64.AppImage` I get the AppImage in a zip file, but if I try to extract that in KDE Plasma I get an error saying that it's not a zip file. 7zip doesn't let me extract either with `7z e <filename>`. But if I type `file <filename>` in terminal I get the message 
```
PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip: Zip archive data, at least v2.0 to extract
```
I ran that file as an executable because I thought that maybe some packaging error was happening but I got the error 
```
invalid file (bad magic number): Exec format error
```

**Comment by luni3359** [comment]
I forgot to mention that AppImages from PolyMC releases are normal AppImage files and run without any problems, but I tried extracting or running other AppImage builds from Github Actions but I still had no luck.

Please let me know what steps to take and also have a look at this issue about putting AppImages in zip files.
https://github.com/cjcliffe/CubicSDR/issues/334

**Comment by txtsd** [comment]
@luni3359 Dev builds come in zip files because that's a limitation of GitHub Actions.
Actual releases from the Releases page aren't unnecessarily zipped.

Not sure why it can't unzip though. Try a different tool?

**Comment by luni3359** [comment]
Nothing is working. Here's the output of the commands I ran:
`unzip:`
```
user@pc:~/Desktop$  unzip PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip 
Archive:  PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip or
        PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip.zip, and cannot find PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip.ZIP, period.
```
`7zip:`
```
user@pc:~/Desktop$  7z e PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=ja_JP.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (A0652),ASM,AES-NI)

Scanning the drive for archives:
1 file, 108593144 bytes (104 MiB)

Extracting archive: PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip

ERRORS:
Unexpected end of archive

--
Path = PolyMC-Linux-1a535cf-Release-x86_64.AppImage.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 108593144

    

Archives with Errors: 1

Open Errors: 1
```

**Comment by Scrumplex** [comment]
This sounds like your downloaded files are just corrupt.

**Comment by luni3359** [comment]
I don't know what happened but after redownloading all the files I tested yesterday I cannot experience file corruption anymore. Thank you for your help.
