### ISSUE TITLE
Vanilla Minecraft 1.20.2 failed to run on macos/arm64

### ISSUE THREAD

**Issue by runlevel5** [PolyMC/PolyMC#1604]
### Operating System

macOS 14.0 (23A344) (arm64)

### Hardware

MacBook Pro (16inch, 2021) Apple M1 Pro

### Version of PolyMC

PolyMC 5.1
Commit: 59fa701c2475c6017780d14f60c7b35f67a25ec4
Channel: 59fa701c

### Version of Qt

Qt 6.3.0

### Description of bug

Got error:

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
```

### Steps to reproduce

Simply add a new instance of vanilla 1.20.2 then start the game

### Suspected cause

Definitely related to LWJGL 3.3.2 (specficially to macos-arm64 build)

This issue does NOT occur if I customise LWJGL to use 3.3.1 macos-arm64

I speculate this might be a bug with LWJGL but not entirely sure because the official stock Minecraft launcher does not run into the same issue. However I still reported the error upstream at https://github.com/LWJGL/lwjgl3/issues/926 in hope the core team would provide further guidance.

Perhaps PolyMC could advise or change LWJGL to 3.3.1 for 1.20.2 profile by default?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by runlevel5** [comment]
The 1.20.2 plays perfectly with Prism Launcher

**Comment by runlevel5** [comment]
The LWJGL has confirmed this issue is likely that of PolyMC

**Comment by Easonz41** [comment]
btw if you get out of fullscreen it fixes it. I did it and it worked

**Comment by ghost** [comment]
I'm not fully convinced this is a PolyMC issue, but in the case it is the LWJGL solution looks rather overcomplicated. Might revisit this soon

**Comment by lennondotw** [comment]
Same issue while launching vanilla Minecraft 1.21.1 with Zulu JDK 21 on macOS.

✅ Resolved after change LWJGL version from 3.3.3 to 3.3.1.

```
Minecraft process ID: 66695


[04:45:38] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 121 milliseconds
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Oct 16, 2024 4:45:44 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ac.a(SourceFile:70)
	at fgo.a(SourceFile:2542)
	at fgo.a(SourceFile:2517)
	at net.minecraft.client.main.Main.main(SourceFile:249)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
	at org.lwjgl.system.Library.loadSystem(Library.java:174)
	at org.lwjgl.system.Library.loadSystem(Library.java:64)
	at org.lwjgl.system.Library.<clinit>(Library.java:52)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at fbf.<clinit>(SourceFile:12)
	at fbk.<init>(SourceFile:30)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:48)
	at net.minecraft.client.main.Main.main(SourceFile:236)
	... 7 more
Oct 16, 2024 4:45:44 AM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
```

**Comment by zandercodes** [comment]
Hello everyone, I have been able to fix the problem.
For some reason the MacOS Arm Library is not being downloaded.
After taking a closer look at the “org.lwjgl3.json” file, I noticed that the following entry was still present in version 3.3.1:
```json
{
  "action": "allow",
  "os": {
    "name": "osx-arm64"
  }
}
```
In the current “org.lwjgl3.json” (3.3.3 and 3.3.2) these entries are missing. I don't know if Mojang has hooked something there.
Here I have a patched file of the “org.lwjgl3.json” for version “3.3.3”
[org.lwjgl3.json](https://github.com/user-attachments/files/17527981/org.lwjgl3.json)

Edit:
> ✅ Resolved after change LWJGL version from 3.3.3 to 3.3.1.

Also works with older Version of LWJGL

**Comment by Sneedplex** [comment]
should be fixed please test

**Comment by mungyeomii** [comment]
Where should I put that file?

**Comment by ssebastianoo** [comment]
> Where should I put that file?

did you discover it? I'm trying to do the same thing

**Comment by zandercodes** [comment]
@mungyeomii 
> Where should I put that file?

@ssebastianoo 
> > Where should I put that file?
> 
> did you discover it? I'm trying to do the same thing

1. Edit Instance
2. `Version` -> click `LWJGL 3` -> click `Change version` -> click `3.3.3`
3. click `Customize` -> click `Edit` -> now open the file in Editor or Edit in the Instance "PolyMC/instances/YOURINSTANCE/patches/org.lwjgl3.json" and replace the content with my file [org.lwjgl3.json](https://github.com/user-attachments/files/17527981/org.lwjgl3.json)

**Comment by mungyeomii** [comment]
Thanks

2025년 1월 28일 (화) 오후 9:56, Julian Zander ***@***.***>님이 작성:
