### ISSUE TITLE
libXxf86vm related crash on NixOS for minecraft 1.7.10

### ISSUE THREAD

**Issue by erplsf** [PolyMC/PolyMC#976]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.0

### Description of bug

Launching any modpack for MC 1.7.10 version should work. At the moment it fails with the following crash stack: https://mclo.gs/XBiNwvS.

### Steps to reproduce

Launch the MC 1.7.10 instance using the NixOS config describe below.

### Suspected cause

I believe line 628: https://mclo.gs/XBiNwvS#L628 to be the culprit. I'm running NixOS unstable with the following flake configs: https://github.com/erplsf/.dotfiles/blob/master/flake.lock and using the polymc overlay as mentioned here: https://github.com/PolyMC/PolyMC/blob/develop/nix/NIX.md. My setup or java or libs are not customized in any other way.
I must confess that this "worked yesterday", before I ran `nix flake update ~/.dotfiles` and rebooted my machine. If i'm opening this error in the wrong repo, please excuse me.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by erplsf** [comment]
I've fixed my flake config to actually use the overlay and build from master of this repo - it has fixed the problem, and I'm out of time atm to investigate it further.

**Comment by F0Xde** [comment]
Just wanted to add some details as I couldn't find any other issue regarding this:

It seems the issue affects basically all Minecraft versions, although I have only tested a few. From early alpha up to 1.12 the above link error occurs, while on 1.13 upwards the game is able to start but fails to initialize the sound system.
```
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
[12:21:29] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
```
Of course I don't know whether the OpenAL error actually relates to this issue but both only happen after updating my system flake, including PolyMC from 1.3.2 -> 1.4.0.

Fixing this is not very urgent for me and I haven't got the time or skills to look into it, so I'm just gonna wait and hope the new 1.4.1 release (not yet in nixpkgs) fixes the issues.

**Comment by auroraanna** [comment]
I have this problem too on 1.12 but not above.

**Comment by F0Xde** [comment]
The issue still persists with PolyMC 1.4.1 for me. I think we should reopen or create a corresponding issue in [nixpkgs](https://github.com/NixOS/nixpkgs). 
Can anyone reproduce the original issue and the missing sound with 1.4.1 from nixpkgs-unstable?
